name: 'Build npm package using yarn'

inputs:
  GITHUB_TOKEN:
    description: access to current github repository
    required: true
  GITHUB_GLOBAL_TOKEN:
    description: access to github repositories for legacy packages
    required: false
  NPM_TOKEN:
    description: access token to @tfso NPM registry
    required: false
  FONT_AWESOME_TOKEN:
    description: access token to fortawesome NPM registry
    required: false
  DEFAULT_BUMP: 
    description: may be major, minor or patch, defaults to patch
    required: false
    default: 'patch'
  INITIAL_VERSION:
    description: initial version, nice if migrating from other build platforms
    required: false
  CUSTOM_TAG:
    description: Set a custom tag, useful when generating tag based on f.ex FROM image in a docker image. Setting this tag will invalidate any other settings set!
    required: false
  NODE_VERSION: 
    description: node version, defaults to 14
    required: false
    default: '14'
  PRUNE_PRODUCTION:
    description: prune for production
    required: false
    default: true
  TRUNCATE_PRERELEASE:
    description: truncate branchname to first word
    required: false
    default: false
  YARN_VERSION:
    description: yarn version, defaults to 1
    required: false
    default: '1'

outputs:
  version: 
    description: the full version including 'v', will be prereleased if build is a branch
    value: v${{ steps.yarn-1.outputs.version || steps.yarn-4.outputs.version }}
  prerelease: 
    description: prerelease suffix for PR builds and will truncate branchname to first word ('feature/my-feature' will be 'feature') unless TRUNCATE_PRERELEASE is set to `false`
    value: ${{ steps.yarn-1.outputs.prerelease || steps.yarn-4.outputs.prerelease }}
  deploy: 
    description: always 'true' if main branch, and always 'false' for other branchers except if a commit contains '#deploy_branch'
    value: ${{ steps.yarn-1.outputs.deploy || steps.yarn-4.outputs.deploy }}

runs:
  using: 'composite'     
  steps: 
    - name: yarn 1
      id: yarn-1
      if: inputs.YARN_VERSION == 1
      uses: ./one
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GITHUB_GLOBAL_TOKEN: ${{ inputs.GITHUB_GLOBAL_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
        FONT_AWESOME_TOKEN: ${{ inputs.FONT_AWESOME_TOKEN }}
        DEFAULT_BUMP: ${{ inputs.DEFAULT_BUMP }}
        INITIAL_VERSION: ${{ inputs.INITIAL_VERSION }}
        CUSTOM_TAG: ${{ inputs.CUSTOM_TAG }}
        NODE_VERSION: ${{ inputs.NODE_VERSION }}
        PRUNE_PRODUCTION: ${{ inputs.PRUNE_PRODUCTION }}
        TRUNCATE_PRERELEASE: ${{ inputs.TRUNCATE_PRERELEASE }}

    - name: yarn 4
      id: yarn-4
      if: inputs.YARN_VERSION == 4
      uses: ./four
      with:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        GITHUB_GLOBAL_TOKEN: ${{ inputs.GITHUB_GLOBAL_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}
        FONT_AWESOME_TOKEN: ${{ inputs.FONT_AWESOME_TOKEN }}
        DEFAULT_BUMP: ${{ inputs.DEFAULT_BUMP }}
        INITIAL_VERSION: ${{ inputs.INITIAL_VERSION }}
        CUSTOM_TAG: ${{ inputs.CUSTOM_TAG }}
        NODE_VERSION: ${{ inputs.NODE_VERSION }}
        PRUNE_PRODUCTION: ${{ inputs.PRUNE_PRODUCTION }}
        TRUNCATE_PRERELEASE: ${{ inputs.TRUNCATE_PRERELEASE }}
