### Github workflow for local test and development 
### act -W .\.github\workflows\test.yml -v -s GITHUB_TOKEN=##################

name: Schematest
description: 'Schematest for API using schemathesis'

inputs:
  AUTH_TOKEN:
    description: 'Auth Token'
    required: false
    default: ''
  SWAGGERPATH:
    description: 'Swagger Path'
    required: false
    default: 'https://localhost:3000/swagger.json'
  GITHUB_TOKEN:
    description: 'Github Token'
    required: false
  XTFSO_LICENSE:
    description: 'XTFSO License'
    required: false
    default: '82cf9f16-8366-48fc-96b0-2f683dea79bc;;'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - uses: BSFishy/pip-action@v1
      with:
        packages: |
          schemathesis

    - name: Schemacheck (Auth)
      if: inputs.AUTH_TOKEN
      id: schemacheck
      run: | 
        echo "Running schemathesis with auth token"
        st run -H "X-Tfso-License: ${{ inputs.XTFSO_LICENSE }}" -H "Authorization: Bearer ${{ inputs.AUTH_TOKEN }}" ${{ inputs.SWAGGERPATH }} --request-tls-verify=false --checks response_schema_conformance --wait-for-schema=5 --junit-xml=report.xml
    
    - name: Schemacheck (No Auth)
      id: schemacheck
      if: inputs.AUTH_TOKEN == ''
      run: | 
        echo "Running schemathesis without auth token"
        st run -H "X-Tfso-License: ${{ inputs.XTFSO_LICENSE }}" ${{ inputs.SWAGGERPATH }} --request-tls-verify=false --checks response_schema_conformance --wait-for-schema=5 --junit-xml=report.xml
      shell: bash

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: 'report.xml'