name: 'SemVer title checker'
description: 'Validates if a PR title ends with a hint on how to version on merge. Can be #patch, #minor, #major or #none'
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      name: Check title
      with:
        script: |
          const title = context.payload.pull_request.title
          const semverTags = [ '#patch', '#minor', '#major', '#none' ]
          if (!semverTags.some(tag => title.endsWith(tag))) {
            core.setFailed(`PR title must end with one of the following semver tags: ${semverTags.join(', ')}`)
          }
          