name: 'Setup'
description: ''

inputs:
  environment:
    description: Environment
    default: ${{ env.DEPLOYMENT_ENVIRONMENT }}
    required: false

  services:
    description: Services
    default: ${{ env.SERVICE_NAME }}
    required: false

outputs:
  version: 
    description: the full version not including 'v', will be prereleased if build is a branch
    value: ${{ steps.semver.outputs.fullversion }}
  prerelease: 
    description: prerelease suffix for PR builds and will truncate branchname to first word ('feature/my-feature' will be 'feature') unless TRUNCATE_PRERELEASE is set to `false`
    value: ${{ steps.semver.outputs.prerelease }}
  environment: 
    description: environment
    value: ${{ steps.environment.outputs.result }}
  services: 
    description: services
    value: ${{ steps.script.outputs.result }}

runs:
  using: 'composite'
  steps: 
    - name: extract tag version
      id: semver 
      uses: booxmedialtd/ws-action-parse-semver@v1.4.7
      with:
        input_string: ${{ github.ref }}
        version_extractor_regex: 'refs\/tags\/v(.*)$'

    - name: get environment
      uses: actions/github-script@v6
      id: environment
      with:
        result-encoding: string
        default: ${{ inputs.environment }}
    - name: extract services
      uses: actions/github-script@v6
      id: script
      with:
        result-encoding: string
        script: |
          if(/^\s*[\[{][\s\S]*[\]}]\s*$/.test(inputs.services)) {
            return JSON.stringify([].concat(...[JSON.parse(inputs.services)]))
          }
          else {
            return JSON.stringify(
              String(inputs.services)
                .split(/[\n]/i)
                .filter(line => line.length > 0)
                .map(line => (
                  /(\w+=([^;]+);)+(\w+=([^;]+))?/g.test(line) == false
                  ? ({ name: line }) 
                  : Object.fromEntries(line
                    .split(/;/g)
                    .map(keyvaluepair => (/(\w+)=(.*)/g.exec(keyvaluepair) ?? []).splice(1))
                  )
              ))
            )
          }