name: 'Setup'
description: ''

inputs:
  environment:
    description: Environment
    required: false

  services:
    description: Services, initServices defaults to env.SERVICE_NAME
    required: false

  githubref:
      description: Github reference
      default: ${{ github.ref }}
      required: false

  regex:
      description: Semver regex
      default: 'refs\/tags\/v(.*)$'
      required: false

outputs:
  version: 
    description: the full version not including 'v', will be prereleased if build is a branch
    value: ${{ steps.semver.outputs.fullversion }}
  prerelease: 
    description: prerelease suffix for PR builds and will truncate branchname to first word ('feature/my-feature' will be 'feature') unless TRUNCATE_PRERELEASE is set to `false`
    value: ${{ steps.semver.outputs.prerelease }}
  environment: 
    description: environment
    value: ${{ steps.initEnvironment.outputs.result }}
  services: 
    description: services
    value: ${{ steps.script.outputs.result }}

runs:
  using: 'composite'
  steps:
    - name: initialize default inputs (environment)
      id: initEnvironment
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
            return process.env.environment || process.env.DEPLOYMENT_ENVIRONMENT;
      env:
        environment: ${{ inputs.environment }}
   
    - name: extract tag version
      id: semver 
      uses: booxmedialtd/ws-action-parse-semver@v1.4.7
      with:
        input_string: ${{ inputs.githubref }}
        version_extractor_regex: ${{ inputs.regex }}

    - name: extract services
      uses: actions/github-script@v6
      id: script
      with:
        result-encoding: string
        script: |
          var service = process.env.services || process.env.SERVICE_NAME;
          if(/^\s*[\[{][\s\S]*[\]}]\s*$/.test(service)) {
            return JSON.stringify([].concat(...[JSON.parse(service)]))
          }
          else {
            return JSON.stringify(
              String(service)
                .split(/[\n]/i)
                .filter(line => line.length > 0)
                .map(line => (
                  /(\w+=([^;]+);)+(\w+=([^;]+))?/g.test(line) == false
                  ? ({ name: line }) 
                  : Object.fromEntries(line
                    .split(/;/g)
                    .map(keyvaluepair => (/(\w+)=(.*)/g.exec(keyvaluepair) ?? []).splice(1))
                  )
              ))
            )
          }
      env:
        services: ${{ inputs.services }}