name: Build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

  workflow_dispatch:
    inputs:
      deploy:
        type: boolean
        required: true
        description: Deploy package

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    if: ${{ (!github.event.workflow && true) || (github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && true) || false }}
    outputs:
      version: ${{ steps.version.outputs.new_tag }}
      major: ${{ steps.version.outputs.major }}
      deploy: ${{ steps.version.outputs.deploy }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: get version
        id: version
        uses: ./get-version
        with:
          # MAJOR: ${{ inputs.MAJOR }}
          WITH_V: true
          TRUNCATE_PRERELEASE: true

  tag:
    if: needs.build.outputs.deploy == 'true' || github.event.inputs.deploy == 'true'
    needs: build
    runs-on: ubuntu-latest
    name: push tag
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: push tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.TFSO_REPO_TAG }}
          CUSTOM_TAG: ${{ needs.build.outputs.version }}

      # - name: push tag
      #   uses: EndBug/latest-tag@v1
      #   with:
      #     ref: ${{ needs.build.outputs.version }}

      # - name: push major tag
      #   uses: EndBug/latest-tag@v1
      #   with:
      #     ref: ${{ needs.build.outputs.major }}
