name: (Release) Package

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+' # only full releases, eg v1.0.1

jobs:
  setup:
    environment: prod
    runs-on: ubuntu-latest
    name: find version
    outputs:
      version: v${{ steps.semver.outputs.fullversion }}
      prerelease: ${{ steps.semver.outputs.prerelease }}
      major: v${{ steps.semver.outputs.major }}
    steps:
      - name: extract tag version
        id: semver
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: 'refs\/tags\/v(.*)$'

  release:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: update major tag
        uses: EndBug/latest-tag@v1
        with: 
          ref: ${{ needs.setup.outputs.major }}
          description: ${{ needs.setup.outputs.major }}

      - uses: tfso/action-changelog-release@v1.1.0
        name: create github release
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
